### ISSUE TITLE
help me pls

### ISSUE THREAD

**Issue by HelpPleaseV6** [MarcuzD/TerraInveditDroid#1]
java.lang.RuntimeException: Unable to start activity ComponentInfo{MarcusD.TerraInvedit/MarcusD.TerraInvedit.InveditActivity}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=89
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2202)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2252)
	at android.app.ActivityThread.access$800(ActivityThread.java:139)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at MarcusD.TerraInvedit.ThrowableApplication.onCreate(ThrowableApplication.java:33)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4415)
	at android.app.ActivityThread.access$1500(ActivityThread.java:139)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1260)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5103)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=89
	at MarcusD.TerraInvedit.InveditActivity.refresh(InveditActivity.java:69)
	at MarcusD.TerraInvedit.InveditActivity.refresh(InveditActivity.java:93)
	at MarcusD.TerraInvedit.InveditActivity.onCreate(InveditActivity.java:57)
	at android.app.Activity.performCreate(Activity.java:5275)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2166)
	... 18 more

**Comment by MarcuzD** [comment]
Could you please provide more information?

What is your Android version?
Are you using a custom ROM, or custom kernel?
What is your SuperSU version? Is "Mount namespace separation" turned off?
What is your Busybox version? Have you tried updating it?

**Comment by jbro129** [comment]
i have the same error 
i am using android 4.1.2
im using the Rocket Tab rom 
SuperSu version 2.49
I dont know what Mount Namespace seperation is or where to find it
and i have busybox installed
