### ISSUE TITLE
Start 

### ISSUE THREAD

**Issue by Nerdatron101** [MarcuzD/TerraInveditDroid#14]
java.lang.NullPointerException: Attempt to read from field 'android.app.Activity android.app.ActivityThread$ActivityClientRecord.activity' on a null object reference
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3528)
	at android.app.ActivityThread.access$1100(ActivityThread.java:156)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:211)
	at MarcusD.TerraInvedit.ThrowableApplication.onCreate(ThrowableApplication.java:33)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4661)
	at android.app.ActivityThread.access$1500(ActivityThread.java:156)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5373)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by MarcuzD** [comment]
Oooh, finally a new bug to work on! Yay :smiley: 
When does this happen? Does it happen all the time? Do you have developer options turned on?

**Comment by MarcuzD** [comment]
This is very weird... What device do you have? What is your Android version?
