### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by evantobing** [MarcuzD/TerraInveditDroid#2]
java.lang.RuntimeException: Unable to start activity ComponentInfo{MarcusD.TerraInvedit/MarcusD.TerraInvedit.InveditActivity}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=89
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2255)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2309)
	at android.app.ActivityThread.access$700(ActivityThread.java:157)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at MarcusD.TerraInvedit.ThrowableApplication.onCreate(ThrowableApplication.java:33)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4592)
	at android.app.ActivityThread.access$1400(ActivityThread.java:157)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5319)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=89
	at MarcusD.TerraInvedit.InveditActivity.refresh(InveditActivity.java:69)
	at MarcusD.TerraInvedit.InveditActivity.refresh(InveditActivity.java:93)
	at MarcusD.TerraInvedit.InveditActivity.onCreate(InveditActivity.java:57)
	at android.app.Activity.performCreate(Activity.java:5326)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2218)
	... 18 more

**Comment by MarcuzD** [comment]
Please read other issues before creating a new one. Look at #1
